name: "dotnet-nuget"
description: Buildkite plugin that pack and build nuget package
author: https://github.com/dx-oss
requirements: ["docker","buildkite-agent","semver"]
configuration:
  version:
    name: string
    description: Version using [CONFIG:VERSION, META:VERSION, ENV:VERSION, ENV:BUILDKITE_TAG] variables if not set (required) 
  provider:
    name: string
    description: Get the nuget provider instead of (NUGET_PROVIDER)
  baseurl:
    name: string
    description: Fetch nuget base url from a env key, default (NUGET_BASEURL)
  pushurl:
    name: string
    description: Where to push the nuget url a env key, default (NUGET_PUSHURL)    
  auth_user:
    name: string
    description: Nuget username key
  auth_secret:
    name: string
    description: Nuget token key
  packages:
    name: array
    description: Nuget packages to push, if not set it pushes all build packages
  image:
    name: string
    description: Docker image use to fetch GitVersion (dxdx/docker-builder-dotnet:2.2)
  runtime:
    name: string
    description: dotnet runtime versions (2.2,3.0,3.1,latest), default (latest=3.1)
  symbols:
    name: int
    description: if value is greater then zero the plugin will push the symbols packages also
  debug:
    name: int
    description: if value is greater then zero the plugin will expose debug information. when the value are 2 it will also expose extended information.
  pull:
    name: int
    description: if value is greater then zero the image would be pull first
  dry:
    name: int
    description: if value is greater then zero the plugin will not pusht the new release
  agent:
    name: string
    description: buildkite-agent binary (https://github.com/buildkite/agent)
  additionalProperties: false
